#!/bin/bash

# =============================================================================
# SCRIPT INSTALASI DOTFILES WRJUNIOR
# Target: Arch Linux (Physical L460 & Virtual Machine QEMU/KVM)
# =============================================================================

set -e # Berhenti jika ada error

# Warna untuk output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${BLUE}==>${NC} ${GREEN}$1${NC}"
}

# 1. Update Sistem & Install Base Dependencies
install_base() {
    print_status "Mengupdate sistem dan menginstal dependensi dasar..."
    sudo pacman -Syu --needed --noconfirm \
        base-devel git curl wget zsh zsh-completions \
        xorg-server xorg-xinit xorg-xset xorg-xrandr \
        bspwm sxhkd polybar rofi kitty dunst feh \
        nautilus ntfs-3g udisks2 gvfs libmtp \
        ttf-firacode-nerd ttf-jetbrains-mono-nerd ttf-font-awesome \
        noto-fonts-emoji papirus-icon-theme materia-gtk-theme \
        polkit-gnome network-manager-applet pamixer brightnessctl \
        ttf-firacode-nerd ttf-jetbrains-mono-nerd ttf-font-awesome ttf-hack-nerd \
        micro firefox
}

# 2. Install Virtualization Tools (QEMU/KVM)
install_virt() {
    print_status "Menginstal QEMU, Virt-Manager, dan Driver Virtual..."
    sudo pacman -S --needed --noconfirm \
        qemu-full virt-manager libvirt dnsmasq iptables-nft \
        spice-vdagent xf86-video-qxl # Driver khusus agar VM smooth
}

# 3. Handle AUR Helper (Yay)
install_yay() {
    if ! command -v yay &> /dev/null; then
        print_status "Memasang AUR Helper (Yay)..."
        git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay && makepkg -si --noconfirm
        cd -
    else
        print_status "Yay sudah terpasang."
    fi
}

# 4. Install AUR Packages (Picom FT-Labs)
install_aur_pkgs() {
    print_status "Memasang paket dari AUR..."
    yay -S --needed --noconfirm picom-ftlabs-git zsh-autosuggestions zsh-syntax-highlighting
}

# 5. Konfigurasi Sistem & Jaringan
setup_system() {
    print_status "Mengatur layanan sistem (Network & Virtualization)..."
    
    # Mencegah IP Ganda: Gunakan NetworkManager saja
    sudo systemctl disable --now systemd-networkd || true
    sudo systemctl enable --now NetworkManager
    
    # Mengaktifkan Virtualisasi
    sudo systemctl enable --now libvirtd
    sudo usermod -aG libvirt $USER
    
    # Mengubah Shell ke Zsh
    sudo chsh -s $(which zsh) $USER
}

# Tambahkan fungsi ini di install.sh
setup_xinit() {
    print_status "Membuat file .xinitrc untuk pemanggilan bspwm..."
    
    # Membuat file dan mengisi dengan perintah eksekusi bspwm
    cat <<EOF > ~/.xinitrc
#!/bin/bash
# .xinitrc generated by wrjunior install script
exec bspwm
EOF

    # Memberikan izin eksekusi agar startx bisa menjalankannya
    chmod +x ~/.xinitrc
    print_status "File .xinitrc berhasil dibuat dan dikonfigurasi."
}

# 6. Deploy Dotfiles
deploy_dots() {
    print_status "Menyalin file konfigurasi..."
    mkdir -p ~/.config
    cp -r .config/* ~/.config/
    cp .zshrc ~/
    
    # Memberi izin eksekusi pada semua script
    print_status "Mengatur izin eksekusi script..."
    find ~/.config -name "*.sh" -exec chmod +x {} +
    chmod +x ~/.config/bspwm/bspwmrc

    # Di dalam install.sh bagian deploy_dots
    print_status "Menyiapkan folder Pictures dan Wallpaper..."
    mkdir -p ~/Pictures
    # Memindahkan pic.png dari repo ke folder Pictures
    if [ -f "pic.png" ]; then
        cp pic.png ~/Pictures/
    fi
}

# --- EKSEKUSI UTAMA ---
clear
echo -e "${YELLOW}Starting Installation...${NC}"

install_base
install_virt
install_yay
install_aur_pkgs
setup_system
setup_xinit
deploy_dots

echo -e "${GREEN}✅ INSTALASI SELESAI!${NC}"
echo -e "${YELLOW}PENTING:${NC}"
echo "1. Silakan REBOOT laptop L460 atau VM Anda."
echo "2. Jika di VM, pastikan Network Interface di polybar/config.ini disesuaikan (enp1s0/eth0)."
